# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 01:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('joined_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submittal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.PositiveIntegerField(unique=True)),
                ('b1_first_name', models.CharField(max_length=256)),
                ('b1_last_name', models.CharField(max_length=256)),
                ('b2_first_name', models.CharField(max_length=256, null=True)),
                ('b2_last_name', models.CharField(max_length=256, null=True)),
                ('b1_employer_name', models.CharField(max_length=256, null=True)),
                ('b2_employer_name', models.CharField(max_length=256, null=True)),
                ('b1_hire_date', models.DateField(max_length=256, null=True)),
                ('b2_hire_date', models.DateField(max_length=256, null=True)),
                ('b1_income_amount', models.PositiveIntegerField(null=True)),
                ('b2_income_amount', models.PositiveIntegerField(null=True)),
                ('b1_pay_frequency', models.CharField(max_length=256, null=True)),
                ('b2_pay_frequency', models.CharField(max_length=256, null=True)),
                ('b1_period_end_date', models.CharField(max_length=256, null=True)),
                ('b2_period_end_date', models.CharField(max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
