# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 03:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submittal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.PositiveIntegerField(unique=True)),
                ('account_type', models.CharField(blank=True, max_length=256)),
                ('loan_officer', models.CharField(blank=True, max_length=256)),
                ('b1_first_name', models.CharField(blank=True, max_length=256)),
                ('b1_last_name', models.CharField(blank=True, max_length=256)),
                ('b2_first_name', models.CharField(blank=True, max_length=256)),
                ('b2_last_name', models.CharField(blank=True, max_length=256)),
                ('b1_employer_name', models.CharField(blank=True, max_length=256)),
                ('b2_employer_name', models.CharField(blank=True, max_length=256)),
                ('b1_hire_date', models.CharField(blank=True, max_length=256)),
                ('b2_hire_date', models.CharField(blank=True, max_length=256)),
                ('b1_income_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('b2_income_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('b1_pay_frequency', models.CharField(blank=True, max_length=256)),
                ('b2_pay_frequency', models.CharField(blank=True, max_length=256)),
                ('b1_period_end_date', models.CharField(blank=True, max_length=256)),
                ('b2_period_end_date', models.CharField(blank=True, max_length=256)),
                ('b1_income_output', models.CharField(blank=True, max_length=256)),
                ('b2_income_output', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('loan_processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submittals', to='submittals.Person')),
            ],
        ),
    ]
